#!/bin/bash
#SBATCH --time=1:00:00
#SBATCH --ntasks=56 --nodes=2
#SBATCH --job-name=lab4_validate
#SBATCH --account=PAS2065

export PGM=lab4_hoke62_hoke62
export OMP_NUM_THREADS=14
export MV2_ENABLE_AFFINITY=0

echo job started at `date`
echo on compute node `cat $PBS_NODEFILE`

cd $SLURM_SUBMIT_DIR
cp input/* $TMPDIR
cd $TMPDIR

echo job started at `date` >>current.out
time srun -n 4 $SLURM_SUBMIT_DIR/${PGM} < PCS_data_test1  >>current.out 2>&1
echo job ended at `date` >>current.out

export SAVEDIR=${SLURM_SUBMIT_DIR}'/data_test.'${SLURM_JOBID}
mkdir ${SAVEDIR}
mv current.out ${SAVEDIR}